### ISSUE TITLE
Change of the repository name

### ISSUE THREAD

**Issue by Arruza17** [Arruza17/ClientBluRoof#7]
As from now on we are going to use the client of the first challenge in the BluRoof Project I think it would be convenient to change the name of the repository to "ClientBluRoof", I don't know how you see it or what you think about it.
![Captura](https://user-images.githubusercontent.com/83445763/148544525-106a6f4f-bd2d-47df-aaa6-754fa61a0604.PNG)

**Comment by AdrianPerez09** [comment]
I agree with this change.

**Comment by yeraysampedro** [comment]
Seems logic to me, go ahead
